on: 
  push:
    branches:
      - master
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: testLemp
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
      
    - name: ğŸ“‚ Sync files
      uses: Samkrikland/FTP-Deploy-Action@4.3.0
      with:
        server: 157.230.36.216
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: var/www/
